name: Auto-merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  enable-auto-merge:
    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
